---

- name: Install SNMP
  apt:
    state: present
    name: "{{ snmp_base_packages }}"
  notify:
    - Restart SNMPD

- name: Configure snmpd
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify:
    - Restart SNMPD

- name: Configure logging
  lineinfile:
    state: present
    line: "SNMPDOPTS='-LS0-4d -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux,mteTrigger,mteTriggerConf -p /run/snmpd.pid'"
    path: /etc/default/snmpd
    regexp: '^SNMPDOPTS='
  notify:
    - Restart SNMPD
- name: Open ports
  ufw:
    port: "161"
    proto: udp
    from_ip: "{{ item }}"
    rule: allow
  with_items: "{{ snmp_master_ips }}"
